java_binary(
    name = "notification-with-listeners",
    srcs = ["NotificationWithListeners.java"],
    main_class = "examples.NotificationWithListeners",
    deps = ["//src/main/java/com/vladmarica/notifier"],
)
