java_binary(
    name = "notifier",
    srcs = glob(["*.java"]),
    main_class = "com.vladmarica.notifier.Notifier",
    deps = [
        "@maven//:com_github_hypfvieh_dbus_java",
        "@maven//:org_slf4j_slf4j_simple",
    ],
)
