java_library(
    name = "notifier",
    srcs = glob(["*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "@maven//:com_github_hypfvieh_dbus_java",
        "@maven//:org_slf4j_slf4j_simple",
    ],
)
